(require 'dired)
(define-key dired-mode-map (kbd "r") 'dired-open-file)

(global-set-key "\C-xk" 'kill-this-buffer)

(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'browse-url-at-point)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ce" 'eval-buffer)
(global-set-key "\C-cg" 'goto-line)
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cm" 'magit-status)
(global-set-key [(menu)] 'dabbrev-expand)

;; s-a is used by unity
(global-set-key [(super c)] 'org-edit-src-code)
(global-set-key [(super e)]
                  '(lambda () (interactive) (org-insert-link '(4))))
;; s-f is used by unity
(global-set-key [(super g)] 'cfw:open-org-calendar)
(global-set-key [(super i)] 'org-toggle-inline-images)
(global-set-key [(super l)] 'org-latex-export-to-latex)
;; s-m is used by unity
(global-set-key [(super o)] 'org-narrow-to-subtree)
(global-set-key [(super r)] 'org-set-property)
(global-set-key [(super s)] 'org-beamer-export-to-pdf)
;; s-s is used by compiz (list of desktops)
;; s-t is used by compiz (trash)
(global-set-key [(super u)] 'org-babel-tangle)
;; s-w is used by compiz 
(global-set-key [(super down)] 'duplicate-line-forward)
(global-set-key [(super up)] 'duplicate-line-backward)
(global-set-key [(super left)] 'move-text-up)
(global-set-key [(super right)] 'move-text-down)
(global-set-key [(f2) (f2)] 'indent-according-to-mode)
(global-set-key [(f2) (f3)] 'copy-region-as-kill)
(global-set-key [(f2) (f4)] 'auto-revert-mode)
(global-set-key [(shift f2)] 'ispell-change-dictionary)
(global-set-key [(control f2)] 'ispell-word)
(global-set-key [(meta f2)] 'ispell-buffer)
(global-set-key [(shift f3)] 'revert-buffer)
(global-set-key [(control f3)] 'replace-string)
(global-set-key [(meta f3)] 'replace-regexp)
(global-set-key [(f6)] 'other-window)
(global-set-key [(meta f6)] 'emacs-lisp-byte-compile-and-load)
(global-set-key [(shift f7)] 'toggle-debug-on-error)
(global-set-key [(f8)] 'ispell-word)
(global-set-key [(f9)] 'org-capture)
