;; cal-sanctoral.el   -*-Emacs-Lisp-*-

;; Copyright (C) 2000,2002 Bill White


;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software
;; Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA



; ======================================================================
; 
; Sanctoral calendar
; ------------------

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; January

(defvar rc-01-01 '((name . "Octave of Christmas; The Blessed Virgin Mary, Mother of God")
                   (emailname . "Octave of Christmas; the Solemnity of the B. V. M., Mother of God")
                   (type . "Solemnity")
                   (color . "White")
                   (rank . 3)))
(defvar rc-01-02 '((name . "Saints Basil the Great and Gregory Nazianzen, bishops and doctors of the Church")
                   (emailname . "the Mem. of Basil the Great and Gregory Nazianzen, bishops and doctors of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-01-03 '((name . "The Most Holy Name of Jesus")
                   (emailname . "the Opt. Mem. of the Most Holy Name of Jesus")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-01-04 '((name . "Saint Elizabeth Ann Seton, religious")
                   (emailname . "the Mem. of Elizabeth Ann Seton, religious")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-01-05 '((name . "Saint John Neumann, bishop")
                   (emailname . "the Mem. of John Neumann, bishop")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-01-06 '((name . "Blessed André Bessette, religious")
                   (emailname . "the Opt. Mem. of Blessed André Bessette, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-01-07 '((name . "Saint Raymond of Penyafort, priest")
                   (emailname . "the Opt. Mem. of Raymond of Penyafort, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-01-13 '((name . "Saint Hilary, bishop and doctor of the Church")
                   (emailname . "the Opt. Mem. of Hilary, bishop and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-01-17 '((name . "Saint Anthony, abbot")
                   (emailname . "the Mem. of Anthony, abbot")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-01-20 '((name . "Saint Fabian, pope and martyr; Saint Sebastian, martyr")
                   (emailname . "the Opt. Mem. of Fabian, pope and martyr; Sebastian, martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-01-21 '((name . "Saint Agnes, virgin and martyr")
                   (emailname . "the Mem. of Agnes, virgin and martyr")
                   (type . "Memorial")
                   (color . "R")
                   (rank . 10)))
(defvar rc-01-22 '((name . "Saint Vincent, deacon and martyr")
                   (emailname . "the Opt. Mem. of Vincent, deacon and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-01-24 '((name . "Saint Francis de Sales, bishop and doctor of the Church")
                   (emailname . "the Mem. of Francis de Sales, bishop and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-01-25 '((name . "The Conversion of Saint Paul, apostle")
                   (emailname . "the Feast of the Conversion of Paul, apostle")
                   (type . "Feast")
                   (color . "White")
                   (rank . 7)))
(defvar rc-01-26 '((name . "Saints Timothy and Titus, bishops")
                   (emailname . "the Mem. of Timothy and Titus, bishops")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-01-27 '((name . "Saint Angela Merici, virgin")
                   (emailname . "the Opt. Mem. of Angela Merici, virgin")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-01-28 '((name . "Saint Thomas Aquinas, priest and doctor of the Church")
                   (emailname . "the Mem. of Thomas Aquinas, priest and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-01-31 '((name . "Saint John Bosco, priest")
                   (emailname . "the Mem. of John Bosco, priest")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; February

(defvar rc-02-02 '((name . "The Presentation of the Lord")
                   (emailname . "the Feast of the Presentation of the Lord")
                   (type . "Feast of the Lord")
                   (color . "White")
                   (rank . 5)))
(defvar rc-02-03 '((name . "Saint Blase, bishop and martyr; Saint Ansgar, bishop")
                   (emailname . "the Opt. Mem. of Blase, bishop and martyr; Ansgar, bishop")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-02-05 '((name . "Saint Agatha, virgin and martyr")
                   (emailname . "the Mem. of Agatha, virgin and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-02-06 '((name . "Saint Paul Miki, priest and martyr, and his companions, martyrs")
                   (emailname . "the Mem. of Paul Miki and companions, martyrs")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-02-08 '((name . "Saint Jerome Emiliani, priest; Saint Josephine Bakhita, virgin")
                   (emailname . "the Opt. Mem. of Jerome Emiliani, priest; Josephine Bakhita, virgin")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-02-10 '((name . "Saint Scholastica, virgin")
                   (emailname . "the Mem. of Scholastica, virgin")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-02-11 '((name . "Our Lady of Lourdes")
                   (emailname . "the Opt. Mem. of Our Lady of Lourdes")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-02-14 '((name . "Saints Cyril, monk, and Methodius, bishop")
                   (emailname . "the Mem. of Cyril, monk, and Methodius, bishop")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-02-17 '((name . "The Seven Founders of the Order of Servites, religious")
                   (emailname . "the Opt. Mem. of the Seven Founders of the Order of Servites")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-02-21 '((name . "Saint Peter Damian, bishop and doctor of the Church")
                   (emailname . "the Opt. Mem. of Peter Damian, bishop and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-02-22 '((name . "The Chair of Peter, apostle")
                   (emailname . "the Feast of the Chair of Peter, apostle")
                   (type . "Feast")
                   (color . "White")
                   (rank . 7)))
(defvar rc-02-23 '((name . "Saint Polycarp, bishop and martyr")
                   (emailname . "the Mem. of Polycarp, bishop and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; March

(defvar rc-03-03 '((name . "Saint Katharine Drexel, virgin")
                   (emailname . "the Opt. Mem. of Katharine Drexel, virgin")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-03-04 '((name . "Saint Casimir")
                   (emailname . "the Opt. Mem. of Casimir")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-03-07 '((name . "Saints Perpetua and Felicity, martyrs ")
                   (emailname . "the Mem. of Perpetua and Felicity, martyrs ")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-03-08 '((name . "Saint John of God, religious")
                   (emailname . "the Opt. Mem. of John of God, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-03-09 '((name . "Saint Frances of Rome, religious")
                   (emailname . "the Opt. Mem. of Frances of Rome, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-03-17 '((name . "Saint Patrick, bishop")
                   (emailname . "the Opt. Mem. of Patrick, bishop")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-03-18 '((name . "Saint Cyril of Jerusalem, bishop and doctor of the Church")
                   (emailname . "the Opt. Mem. of Cyril of Jerusalem, bishop and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-03-19 '((name . "Saint Joseph, husband of the Blessed Virgin Mary")
                   (emailname . "the Solemnity of Joseph, husband of the B. V. M.")
                   (type . "Solemnity")
                   (color . "White")
                   (rank . 3)))
(defvar rc-03-23 '((name . "Saint Turibius de Mogrovejo, bishop")
                   (emailname . "the Opt. Mem. of Turibius de Mogrovejo, bishop")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-03-25 '((name . "The Annunciation of the Lord")
                   (emailname . "the Solemnity of the Annunciation of the Lord")
                   (type . "Solemnity")
                   (color . "White")
                   (rank . 3)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; April

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defvar rc-04-02 '((name . "Saint Francis of Paola, hermit")
		 (emailname . "the Opt. Mem. of Francis of Paola, hermit")
		 (type . "Optional Memorial")
		 (color . "-")
		 (rank . 12)))
(defvar rc-04-04 '((name . "Saint Isidore of Seville, bishop and doctor of the Church")
		 (emailname . "the Opt. Mem. of Isidore of Seville, bishop and doctor of the Church")
		 (type . "Optional Memorial")
		 (color . "-")
		 (rank . 12)))
(defvar rc-04-05 '((name . "Saint Vincent Ferrer, priest")
		 (emailname . "the Opt. Mem. of Vincent Ferrer, priest")
		 (type . "Optional Memorial")
		 (color . "-")
		 (rank . 12)))
(defvar rc-04-07 '((name . "Saint John Baptist de la Salle, priest")
		 (emailname . "the Mem. of John Baptist de la Salle, priest")
		 (type . "Memorial")
		 (color . "White")
		 (rank . 10)))
(defvar rc-04-11 '((name . "Saint Stanislaus, bishop and martyr")
		 (emailname . "the Opt. Mem. of Stanislaus, bishop and martyr")
		 (type . "Optional Memorial")
		 (color . "-")
		 (rank . 12)))
(defvar rc-04-13 '((name . "Saint Martin I, pope and martyr")
		 (emailname . "the Opt. Mem. of Martin I, pope and martyr")
		 (type . "Optional Memorial")
		 (color . "-")
		 (rank . 12)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defvar rc-04-21 '((name . "Saint Anselm, bishop and doctor of the Church")
                   (emailname . "the Opt. Mem. of Anselm, bishop and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-04-23 '((name . "Saint George, martyr; Saint Adalbert, bishop and martyr")
                   (emailname . "the Opt. Mem. of George, martyr; Adalbert, bishop and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-04-24 '((name . "Saint Fidelis of Sigmaringen, priest and martyr")
                   (emailname . "the Opt. Mem. of Fidelis of Sigmaringen, priest and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-04-25 '((name . "Saint Mark, evangelist")
                   (emailname . "the Feast of Mark, evangelist")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-04-28 '((name . "Saint Peter Chanel, priest and martyr; Saint Louis Mary de Montfort, priest")
                   (emailname . "the Opt. Mem. of Peter Chanel, priest and martyr; Louis Mary de Montfort, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-04-29 '((name . "Saint Catherine of Siena, virgin and doctor of the Church")
                   (emailname . "the Mem. of Catherine of Siena, virgin and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defvar rc-04-30 '((name . "Saint Pius V, pope")
                   (emailname . "the Opt. Mem. of Pius V, pope")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; May

(defvar rc-05-01 '((name . "Saint Joseph the Worker")
                   (emailname . "the Opt. Mem. of Joseph the Worker")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-02 '((name . "Saint Athanasius, bishop and doctor of the Church")
                   (emailname . "the Mem. of Athanasius, bishop and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-05-03 '((name . "Saints Philip and James, apostles")
                   (emailname . "the Feast of Philip and James, apostle")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-05-12 '((name . "Saints Nereus and Achilleus, martyrs; Saint Pancras, martyr")
                   (emailname . "the Opt. Mem. of Nereus and Achilleus, martyrs; Pancras, martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-13 '((name . "Our Lady of Fatima")
                   (emailname . "the Opt. Mem. of Our Lady of Fatima")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-14 '((name . "Saint Matthias, apostle")
                   (emailname . "the Feast of Matthias, apostle")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-05-15 '((name . "Saint Isidore the Farmer")
                   (emailname . "the Opt. Mem. of Isidore the Farmer")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-18 '((name . "Saint John I, pope and martyr")
                   (emailname . "the Opt. Mem. of John I, pope and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-20 '((name . "Saint Bernardine of Siena, priest")
                   (emailname . "the Opt. Mem. of Bernardine of Siena, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-21 '((name . "Saint Christopher Magallanes, priest and martyr, and his companions, martyrs")
                   (emailname . "the Opt. Mem. of Christopher Magallanes and his companions, martyrs")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-22 '((name . "Saint Rita of Cascia, religious")
                   (emailname . "the Opt. Mem. of Rita of Cascia, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-25 '((name . "Saint Bede the Venerable, priest and doctor of the Church; Saint Gregory VII, pope; Saint Mary Magdalene de' Pazzi, virgin")
                   (emailname . "the Opt. Mem. of Bede the Venerable, priest and doctor of the Church; Gregory VII, pope; Mary Magdalene de' Pazzi, virgin")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-26 '((name . "Saint Philip Neri, priest")
                   (emailname . "the Mem. of Philip Neri, priest")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-05-27 '((name . "Saint Augustine of Canterbury, bishop")
                   (emailname . "the Opt. Mem. of Augustine of Canterbury, bishop")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-05-31 '((name . "The Visitation of the Blessed Virgin Mary")
                   (emailname . "the Feast of the Visitation of the B. V. M.")
                   (type . "Feast")
                   (color . "White")
                   (rank . 7)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; June

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defvar rc-06-01 '((name . "Saint Justin, martyr")
                   (emailname . "the Mem. of Justin, martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-06-02 '((name . "Saints Marcellinus and Peter, martyrs")
                   (emailname . "the Opt. Mem. of Marcellinus and Peter, martyrs")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-06-03 '((name . "Saint Charles Lwanga and his companions, martyrs")
                   (emailname . "the Mem. of Charles Lwanga and his companions, martyrs")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-06-05 '((name . "Saint Boniface, bishop and martyr")
                   (emailname . "the Mem. of Boniface, bishop and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-06-06 '((name . "Saint Norbert, bishop")
                   (emailname . "the Opt. Mem. of Norbert, bishop")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-06-09 '((name . "Saint Ephrem, deacon and doctor of the Church")
                   (emailname . "the Opt. Mem. of Ephrem, deacon and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defvar rc-06-11 '((name . "Saint Barnabas, apostle")
                   (emailname . "the Mem. of Barnabas, apostle")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-06-13 '((name . "Saint Anthony of Padua, priest and doctor of the Church")
                   (emailname . "the Mem. of Anthony of Padua, priest and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-06-19 '((name . "Saint Romuald, abbot")
                   (emailname . "the Opt. Mem. of Romuald, archbishop")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-06-21 '((name . "Saint Aloysius Gonzaga, religious")
                   (emailname . "the Mem. of Aloysius Gonzaga, religious")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-06-22 '((name . "Saint Paulinus of Nola, bishop; Saints John Fisher, bishop and martyr and Thomas More, martyr")
                   (emailname . "the Opt. Mem. of Paulinus of Nola, bishop; John Fisher, bishop and martyr and Thomas More, martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-06-24 '((name . "The Birth of John the Baptist")
                   (emailname . "the Solemnity of the Birth of John the Baptist")
                   (type . "Solemnity")
                   (color . "White")
                   (rank . 3)))
(defvar rc-06-27 '((name . "Saint Cyril of Alexandria, bishop and doctor of the Church")
                   (emailname . "the Opt. Mem. of Cyril of Alexandria, bishop and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-06-28 '((name . "Saint Irenaeus, bishop and martyr")
                   (emailname . "the Mem. of Irenaeus, bishop and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-06-29 '((name . "Saints Peter and Paul, apostles")
                   (emailname . "the Solemnity of Peter and Paul, apostles")
                   (type . "Solemnity")
                   (color . "Red")
                   (rank . 3)))
(defvar rc-06-30 '((name . "The First Martyrs of the Church of Rome")
                   (emailname . "the Opt. Mem. of the First Martyrs of the Church of Rome")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; July

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defvar rc-07-01 '((name . "Blessed Junipero Serra, priest and religious")
                   (emailname . "the Opt. Mem. of Blessed Junipero Serra, priest and religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-03 '((name . "Saint Thomas, apostle")
                   (emailname . "the Feast of Thomas, apostle")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-07-04 '((name . "Saint Elizabeth of Portugal, religious")
                   (emailname . "the Opt. Mem. of Elizabeth of Portugal, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-05 '((name . "Saint Anthony Mary Zaccaria, priest")
                   (emailname . "the Opt. Mem. of Anthony Mary Zaccaria, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-06 '((name . "Saint Maria Goretti, virgin and martyr")
                   (emailname . "the Opt. Mem. of Maria Goretti, virgin and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-09 '((name . "Saint Augustine Zhao Rong, priest and martyr, and his companions, martyrs")
                   (emailname . "the Opt. Mem. of Augustine Zhao Rong, priest and martyr, and his companions, martyrs")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-11 '((name . "Saint Benedict, abbot")
                   (emailname . "the Mem. of Benedict, abbot")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-07-13 '((name . "Saint Henry")
                   (emailname . "the Opt. Mem. of Henry")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-14 '((name . "Blessed Kateri Tekakwitha, virgin")
                   (emailname . "the Mem. of Blessed Kateri Tekakwitha, virgin")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-07-15 '((name . "Saint Bonaventure, bishop and doctor of the Church")
                   (emailname . "the Mem. of Bonaventure, bishop and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-07-16 '((name . "Our Lady of Mount Carmel")
                   (emailname . "the Opt. Mem. of Our Lady of Mount Carmel")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-18 '((name . "Saint Camillus de Lellis, priest")
                   (emailname . "the Opt. Mem. of Camillus de Lellis, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-20 '((name . "Saint Apollinarus, bishop and martyr")
                   (emailname . "the Opt. Mem. of Apollinarus, bishop and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-21 '((name . "Saint Lawrence of Brindisi, priest and doctor of the Church")
                   (emailname . "the Opt. Mem. of Lawrence of Brindisi, priest and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-22 '((name . "Saint Mary Magdalene")
                   (emailname . "the Mem. of Mary Magdalene")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-07-23 '((name . "Saint Bridget of Sweden, religious")
                   (emailname . "the Opt. Mem. of Bridget, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-24 '((name . "Saint Sharbel Makhluf, priest")
                   (emailname . "the Opt. Mem. of Bridget, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-25 '((name . "Saint James, apostle")
                   (emailname . "the Feast of James, apostle")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-07-26 '((name . "Saints Joachim and Anne, parents of the Blessed Virgin Mary")
                   (emailname . "the Mem. of Joachim and Anne, parents of the B. V. M.")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-07-29 '((name . "Saint Martha")
                   (emailname . "the Mem. of Martha")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-07-30 '((name . "Saint Peter Chrysologus, bishop and doctor of the Church")
                   (emailname . "the Opt. Mem. of Peter Chrysologus, bishop and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-07-31 '((name . "Saint Ignatius of Loyola, priest")
                   (emailname . "the Mem. of Ignatius of Loyola, priest")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)
                   ))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; August

(defvar rc-08-01 '((name . "Saint Alphonsus Liguori, bishop and doctor of the Church")
                   (emailname . "the Mem. of Alphonsus Liguori, bishop and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-02 '((name . "Saint Eusebius of Vercelli, bishop; Saint Peter Julian Eymard, priest")
                   (emailname . "the Opt. Mems. of Eusebius of Vercelli, bishop; Peter Julian Eymard, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-08-04 '((name . "Saint John Mary Vianney, priest")
                   (emailname . "the Mem. of John Vianney, priest")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-05 '((name . "The Dedication of the Basilica of Saint Mary in Rome")
                   (emailname . "the Opt. Mem. of the Dedication of the Basilica of Saint Mary in Rome")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-08-06 '((name . "The Transfiguration of the Lord")
                   (emailname . "the Feast of the Transfiguration of the Lord")
                   (type . "Feast of the Lord")
                   (color . "White")
                   (rank . 5)))
(defvar rc-08-07 '((name . "Saint Sixtus II, pope and martyr, and his companions, martyrs; Saint Cajetan, priest")
                   (emailname . "the Opt. Mems. of Sixtus II, pope and martyr, and his companions, martyrs; Cajetan, priest]")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-08-08 '((name . "Saint Dominic, priest")
                   (emailname . "the Mem. of Dominic, priest")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-09 '((name . "Saint Teresa Benedicta of the Cross, virgin and martyr")
                   (emailname . "the Mem. of Teresa Benedicta of the Cross, virgin and martyr")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-10 '((name . "Saint Lawrence, deacon and martyr")
                   (emailname . "the Feast of Lawrence, deacon and martyr")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-08-11 '((name . "Saint Clare, virgin")
                   (emailname . "the Mem. of Clare, virgin")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-13 '((name . "Saints Pontian, pope and martyr and Hippolytus, priest and martyr")
                   (emailname . "the Opt. Mem. of Pontian, pope and martyr and Hippolytus, priest and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-08-14 '((name . "Saint Maximilian Mary Kolbe, priest and martyr")
                   (emailname . "the Mem. of Maximilian Mary Kolbe, priest and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-08-15 '((name . "The Assumption of the Blessed Virgin Mary")
                   (emailname . "the Solemnity of the Assumption of the B. V. M.")
                   (type . "Solemnity")
                   (color . "White")
                   (rank . 3)))
(defvar rc-08-16 '((name . "Saint Stephen of Hungary")
                   (emailname . "the Opt. Mem. of Stephen of Hungary")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-08-18 '((name . "Saint Jane Frances de Chantal, religious")
                   (emailname . "the Opt. Mem. of Jane Frances de Chantal, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-08-19 '((name . "Saint John Eudes, priest")
                   (emailname . "the Opt. Mem. of John Eudes, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-08-20 '((name . "Saint Bernard, abbot and doctor of the Church")
                   (emailname . "the Mem. of Bernard, abbot and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-21 '((name . "Saint Pius X, pope")
                   (emailname . "the Mem. of Pius X, pope")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-22 '((name . "The Queenship of the Blessed Virgin Mary")
                   (emailname . "the Mem. of the Queenship of the Blessed Virgin Mary")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-23 '((name . "Saint Rose of Lima, virgin")
                   (emailname . "the Opt. Mem. of Rose of Lima, virgin")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-08-24 '((name . "Saint Bartholomew, apostle")
                   (emailname . "the Feast of Bartholomew, apostle")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-08-25 '((name . "Saint Louis of France; Saint Joseph Calasanz, priest")
                   (emailname . "the Opt. Mem. of Louis of France; Joseph Calasanz, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-08-27 '((name . "Saint Monica")
                   (emailname . "the Mem. of Monica")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-28 '((name . "Saint Augustine, bishop and doctor of the Church")
                   (emailname . "the Mem. of Augustine, bishop and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-08-29 '((name . "The Martyrdom of John the Baptist, martyr")
                   (emailname . "the Mem. of the Martyrdom of John the Baptist, martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; September

(defvar rc-09-03 '((name . "Saint Gregory the Great, pope and doctor of the Church")
                   (emailname . "the Mem. of Gregory the Great, pope and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-09-08 '((name . "The Birth of the Blessed Virgin Mary")
                   (emailname . "the Feast of the Birth of the B. V. M.")
                   (type . "Feast")
                   (color . "White")
                   (rank . 7)))
(defvar rc-09-09 '((name . "Saint Peter Claver, priest")
                   (emailname . "the Mem. of Peter Claver, priest")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-09-12 '((name . "The Most Holy Name of the Blessed Virgin Mary")
                   (emailname . "the Opt. Mem. of the Most Holy Name of the Blessed Virgin Mary")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-09-13 '((name . "Saint John Chrysostom, bishop and doctor of the Church")
                   (emailname . "the Mem. of John Chrysostom, bishop and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-09-14 '((name . "The Exaltation of the Holy Cross")
                   (emailname . "the Feast of the Exaltation of the Holy Cross")
                   (type . "Feast of the Lord")
                   (color . "Red")
                   (rank . 5)))
(defvar rc-09-15 '((name . "Our Lady of Sorrows")
                   (emailname . "the Mem. of Our Lady of Sorrows")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-09-16 '((name . "Saints Cornelius, pope and martyr and Cyprian, bishop and martyr")
                   (emailname . "the Mem. of Cornelius, pope and martyr and Cyprian, bishop and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-09-17 '((name . "Saint Robert Bellarmine, bishop and doctor of the Church")
                   (emailname . "the Opt. Mem. of Robert Bellarmine, bishop and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-09-19 '((name . "Saint Januarius, bishop and martyr")
                   (emailname . "the Opt. Mem. of Janurius, bishop and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-09-20 '((name . "Saint Andrew Kim Taegon, priest and martyr and Saint Paul Chong Hasang and their companions, martyrs")
                   (emailname . "the Mem. of Andrew Kim Taegon, priest and martyr, Paul Chong Hasang, martyr, and their companions, martyrs")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-09-21 '((name . "Saint Matthew, apostle and evangelist")
                   (emailname . "the Feast of Matthew, apostle and evangelist")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-09-23 '((name . "Saint Pio of Pietreclina, priest")
                   (emailname . "the Mem. of Pio of Pietreclina, priest")
                   (type . "Memorial")
                   (color . "-")
                   (rank . 10)))
(defvar rc-09-26 '((name . "Saints Cosmas and Damian, martyrs")
                   (emailname . "the Opt. Mem. of Cosmas and Damian, martyrs")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-09-27 '((name . "Saint Vincent de Paul, priest")
                   (emailname . "the Mem. of Vincent de Paul, priest")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-09-28 '((name . "Saint Wenceslaus, martyr; Saint Lawrence Ruiz and his companions, martyrs")
                   (emailname . "the Opt. Mem. of Wenceslaus, martyr; Lawrence Ruiz and his companions, martyrs")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-09-29 '((name . "Saints Michael, Gabriel, and Raphael, archangels")
                   (emailname . "the Feast of Michael, Gabriel, and Raphael, archangels")
                   (type . "Feast")
                   (color . "White")
                   (rank . 7)))
(defvar rc-09-30 '((name . "Saint Jerome, priest and doctor of the Church")
                   (emailname . "the Mem. of Jerome, priest and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; October

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defvar rc-10-01 '((name . "Saint Thérèse of the Child Jesus, virgin and doctor of the Church")
                   (emailname . "the Mem. of Thérèse of the Child Jesus, virgin and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-10-02 '((name . "The Guardian Angels")
                   (emailname . "the Mem. of the Guardian Angels")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-10-04 '((name . "Saint Francis of Assisi, religious")
                   (emailname . "the Mem. of Francis of Assisi, religious")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-10-06 '((name . "Saint Bruno, priest; Blessed Marie-Rose Durocher, virgin")
                   (emailname . "the Opt. Mem. of Bruno, priest; Blessed Marie-Rose Durocher, virgin")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-10-07 '((name . "Our Lady of the Rosary")
                   (emailname . "the Mem. of Our Lady of the Rosary")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-10-09 '((name . "Saint Denis, bishop and martyr and his companions, martyrs; Saint John Leonardi, priest")
                   (emailname . "the Opt. Mem. of Denis, bishop and martyr and his companions, martyrs; John Leonardi, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-10-14 '((name . "Saint Callistus I, pope and martyr")
                   (emailname . "the Opt. Mem. of Callistus I, pope and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-10-15 '((name . "Saint Teresa of Avila, virgin and doctor of the Church")
                   (emailname . "the Mem. of Teresa of Avila, virgin and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-10-16 '((name . "Saint Hedwig, religious; Saint Margaret Mary Alacoque, virgin")
                   (emailname . "the Opt. Mem. of Hedwig, religious; Margaret Mary Alacoque, virgin")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-10-17 '((name . "Saint Ignatius of Antioch, bishop and martyr")
                   (emailname . "the Mem. of Ignatius of Antioch, bishop and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-10-18 '((name . "Saint Luke, evangelist")
                   (emailname . "the Feast of Luke, evangelist")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-10-19 '((name . "Saints Isaac Jogues and John de Brébeuf, priests and martyrs, and their companions, martyrs")
                   (emailname . "the Mem. of Isaac Jogues and John de Brébeuf, priests and martyrs, and their companions, martyrs")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-10-20 '((name . "Saint Paul of the Cross, priest")
                   (emailname . "the Opt. Mem. of Paul of the Cross, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-10-23 '((name . "Saint John of Capistrano, priest")
                   (emailname . "the Opt. Mem. of John of Capistrano, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-10-24 '((name . "Saint Anthony Mary Claret, bishop")
                   (emailname . "the Opt. Mem. of Anthony Mary Claret, bishop")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-10-28 '((name . "Saints Simon and Jude, apostles")
                   (emailname . "the Feast of Simon and Jude, apostles")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; November

(defvar rc-11-01 '((name . "All Saints")
                   (emailname . "the Solemnity of All Saints")
                   (type . "Solemnity")
                   (color . "White")
                   (rank . 3)))
(defvar rc-11-02 '((name . "The Commemoration of All the Faithful Departed (All Souls)")
                   (emailname . "the Feast of the Commemoration of All the Faithful Departed (All Souls)")
                   (type . "Feast")
                   (color . "White")
                   (rank . 7)))
(defvar rc-11-03 '((name . "Saint Martin de Porres, religious")
                   (emailname . "the Opt. Mem. of Martin de Porres, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-11-04 '((name . "Saint Charles Borromeo, bishop")
                   (emailname . "the Mem. of Charles Borromeo, bishop")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-11-09 '((name . "The Dedication of the Lateran Basilica in Rome")
                   (emailname . "the Feast of the Dedication of the Lateran Basilica in Rome")
                   (type . "Feast")
                   (color . "White")
                   (rank . 7)))
(defvar rc-11-10 '((name . "Saint Leo the Great, pope and doctor of the Church")
                   (emailname . "the Mem. of Leo the Great, pope and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-11-11 '((name . "Saint Martin of Tours, bishop")
                   (emailname . "the Mem. of Martin of Tours, bishop")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-11-12 '((name . "Saint Josaphat, bishop and martyr")
                   (emailname . "the Mem. of Josaphat, bishop and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-11-13 '((name . "Saint Frances Xavier Cabrini, virgin")
                   (emailname . "the Mem. of Frances Xavier Cabrini, virgin")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-11-15 '((name . "Saint Albert the Great, bishop and doctor of the Church")
                   (emailname . "the Opt. Mem. of Albert the Great, bishop and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-11-16 '((name . "Saint Margaret of Scotland; Saint Gertrude the Great, virgin")
                   (emailname . "the Opt. Mem. of Margaret of Scotland; Gertrude the Great, virgin")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-11-17 '((name . "Saint Elizabeth of Hungary, religious")
                   (emailname . "the Mem. of Elizabeth of Hungary, religious")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-11-18 '((name . "The Dedication of the Basilicas of the Apostles Peter and Paul in Rome; Saint Rose Philippine Duchesne, religious")
                   (emailname . "the Opt. Mem. of the Dedication of the Basilicas of the Apostles Peter and Paul in Rome; Rose Philippine Duchesne, religious")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-11-21 '((name . "The Presentation of the Blessed Virgin Mary")
                   (emailname . "the Mem. of the Presentation of the Blessed Virgin Mary")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-11-22 '((name . "Saint Cecilia, virgin and martyr")
                   (emailname . "the Mem. of Cecilia, virgin and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-11-23 '((name . "Saint Clement I, pope and martyr; Saint Columban, abbot; Blessed Miguel Agustín Pro, priest and martyr")
                   (emailname . "the Opt. Mem. of Clement I, pope and martyr; Columban, abbot; Blessed Miguel Agustín Pro, priest and martyri")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-11-24 '((name . "Saint Andrew Dung-Lac, priest and martyr, and his companions, martyrs")
                   (emailname . "the Mem. of Andrew Dung-Lac, priest and martyr, and his companions, martyrs")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-11-25 '((name . "Saint Catherine of Alexandria, virgin and martyr")
                   (emailname . "the Opt. Mem. of Catherine of Alexandria, virgin and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-11-30 '((name . "Saint Andrew, apostle")
                   (emailname . "the Feast of Andrew, apostle")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; December

(defvar rc-12-03 '((name . "Saint Frances Xavier, priest")
                   (emailname . "the Mem. of Frances Xavier, priest")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-12-04 '((name . "Saint John of Damascus, priest and doctor of the Church")
                   (emailname . "the Opt. Mem. of John of Damascus, priest and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-12-06 '((name . "Saint Nicholas, bishop")
                   (emailname . "the Opt. Mem. of Nicholas, bishop")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-12-07 '((name . "Saint Ambrose, bishop and doctor of the Church")
                   (emailname . "the Mem. of Ambrose, bishop and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-12-08 '((name . "The Immaculate Conception of the Blessed Virgin Mary")
                   (emailname . "the Solemnity of the Immaculate Conception of the B. V. M.")
                   (type . "Solemnity")
                   (color . "White")
                   (rank . 3)))
(defvar rc-12-09 '((name . "Blessed Juan Diego (Cuatitlatoatzin)")
                   (emailname . "the Opt. Mem. of Blessed Juan Diego (Cuatitlatoatzin)")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-12-11 '((name . "Saint Damasus I, pope")
                   (emailname . "the Opt. Mem. of Damasus I, pope")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-12-12 '((name . "Our Lady of Guadalupe")
                   (emailname . "the Mem. of Our Lady of Guadalupe")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-12-13 '((name . "Saint Lucy, virgin and martyr")
                   (emailname . "the Mem. of Lucy, virgin and martyr")
                   (type . "Memorial")
                   (color . "Red")
                   (rank . 10)))
(defvar rc-12-14 '((name . "Saint John of the Cross, priest and doctor of the Church")
                   (emailname . "the Mem. of John of the Cross, priest and doctor of the Church")
                   (type . "Memorial")
                   (color . "White")
                   (rank . 10)))
(defvar rc-12-21 '((name . "Saint Peter Canisius, priest and doctor of the Church")
                   (emailname . "the Opt. Mem. of Peter Canisius, priest and doctor of the Church")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-12-23 '((name . "Saint John of Kanty, priest")
                   (emailname . "the Opt. Mem. of John of Kanty, priest")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-12-26 '((name . "Saint Stephen, first martyr")
                   (emailname . "the Feast of Stephen, first martyr")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-12-27 '((name . "Saint John, apostle and evangelist")
                   (emailname . "the Feast of John, apostle and evangelist")
                   (type . "Feast")
                   (color . "White")
                   (rank . 7)))
(defvar rc-12-28 '((name . "The Holy Innocents, martyrs")
                   (emailname . "the Feast of the Holy Innocents, martyrs")
                   (type . "Feast")
                   (color . "Red")
                   (rank . 7)))
(defvar rc-12-29 '((name . "Saint Thomas Becket, bishop and martyr")
                   (emailname . "the Opt. Mem. of Thomas Becket, bishop and martyr")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))
(defvar rc-12-31 '((name . "Saint Sylvester I, pope")
                   (emailname . "the Opt. Mem. of Sylvester I, pope")
                   (type . "Optional Memorial")
                   (color . "-")
                   (rank . 12)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; provide the package

(provide 'cal-sanctoral)
